project_name: 'online_transformers'
type: 'POPGym'
env: 'RepeatPreviousMedium'
log_name: 'POPGym/RepeatPrevious/RepeatPreviousMedium/DTQN/DTQN_RepeatPreviousMedium_SHORT_TERM'
logger: 'tensorboard'




seed: 42
context: 30

disable_wandb: False
time_limit: null
eval_mode: False
model: 'DTQN'
num_steps: 1000000
tuf: 10000
lr: 3.0e-4
batch: 32
buf_size: 500000 #5000000
eval_frequency: 5000
eval_episodes: 100
device: 'cuda:0'
obsembed: 8
inembed: 128
save_policy: False
verbose: True
render: False
history: True
heads: 8
layers: 2
dropout: 0
gate: 'res' # 'gru'
identity: False
pos: 1  #choices=[1, 0, "sin"],
