# @package _global_
tags: ["HalfCheetah-v4"]
project_name: "ReLiT"
seed: 1
steps: 100000000
log_interval: 10000
eval_interval: 1000000
eval_episodes: 1
# eval_only: false
videos: true
record_fps: 30
save_interval: 1000000
save_dir: "./checkpoints"
save_tag: "relit_half-cheetah-v4"
restore: true
continuous_actions: true
task: 
  task: "mujoco"
  env_name: "HalfCheetah-v4"
  # max_episode_steps = 1000

trainer:
  agent: a2c
  rollout_len: 256
  num_envs: 8
  seq_model:
    name: relit
    n_layers: 4
    d_model: 128
    d_head: 64
    d_ffc: 128
    n_heads: 4
    update_rule: projected_sigmoid
    flow: gtrxl
    kernel:
      name: pp_relu
      nu: 2
    reset_hidden_on_terminate: true
  d_actor: 128
  d_critic: 128
  gamma: 0.99
  lamb: 0.95
  entropy_coef: 0.001
  value_coef: 0.5
  max_grad_norm: 0.5
  optimizer:
    learning_rate: 0.0001

use_wandb: true